# action.yml
name: 'Transponder'
description: 'Ingests repo data into J1'
inputs:
  j1_api_key:
    description: 'The API for JupiterOne'
    required: true
  j1_api_domain:
    description: 'The API domain for JupiterOne'
    required: true
  j1_account_id:
    description: 'The account id for JupiterOne'
    required: true
  transponder_config:
    description: 'The config file for your transponder'
    required: true
runs:
  using: "composite"    
  steps:
    - name: Transponder
      env: 
        J1_API_KEY: ${{ inputs.j1_api_key }}
        J1_API_DOMAIN: ${{ inputs.j1_api_domain }}
        J1_ACCOUNT_ID: ${{ inputs.j1_account_id }}
        TRANSPONDER_CONFIG: ${{ inputs.transponder_config }}
      run: |
          yarn add --dev @jupiterone/transponder
          yarn add --dev @jupiterone/transponder-core-plugin
          yarn transponder --config $TRANSPONDER_CONFIG
      shell: bash
