# action.yml
name: 'Transponder'
description: 'Ingests repo data into J1'
inputs:
  j1_api_key:
    description: 'The API for JupiterOne'
    required: true
  j1_api_domain:
    description: 'The API domain for JupiterOne'
    required: true
  j1_account_id:
    description: 'The account id for JupiterOne'
    required: true
  transponder_docker_image:
    description: 'docker image to use'
    required: true
runs:
  using: "composite"    
  steps:
    - name: Transponder
      env: 
        transponder_docker_image: ${{ inputs.transponder_docker_image }}
        j1_api_key: ${{ inputs.j1_api_key }}
        j1_api_domain: ${{ inputs.j1_api_domain }}
        j1_account_id: ${{ inputs.j1_account_id }}
      run: |
          docker pull ::add-mask::$transponder_docker_image
      shell: bash
