# action.yml
name: 'Transponder'
description: 'Ingests repo data into J1'
inputs:
  j1_api_key:
    description: 'The API for JupiterOne'
    required: true
  j1_api_domain:
    description: 'The API domain for JupiterOne'
    required: true
  j1_account_id:
    description: 'The account id for JupiterOne'
runs:
  using: "composite"    
  steps:
    - name: Transponder
      with: 
        transponder_docker_image: ${{ secrets.TRANSPONDER_DOCKER_IMAGE }}
        j1_api_key: ${{ inputs.j1_api_key }}
        j1_api_domain: ${{ inputs.j1_api_domain }}
        j1_account_id: ${{ inputs.j1_account_id }}
      run: |
          TRANSPONDER_DOCKER_IMAGE="::add-mask::$transponder_docker_image"
          docker pull $TRANSPONDER_DOCKER_IMAGE
          docker run --rm -v `pwd`:`pwd` -w `pwd` \
            -e J1_API_KEY="::add-mask::$j1_api_key" \
            -e J1_API_DOMAIN="::add-mask::$j1_api_domain" \
            -e J1_ACCOUNT_ID="::add-mask::$j1_account_id" \
            $TRANSPONDER_DOCKER_IMAGE
      shell: bash
